[package]
name = "time_calc_rs"
version = "0.1.0"
authors = ["mike"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.0-alpha-0"
chrono = "0.4"
